
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Käytetään Replitiin tallennettuja ympäristömuuttujia (Secrets) Vite.js-muodossa
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "";
const SUPABASE_ANON_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || "";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Huom: Parempi käytäntö olisi käyttää backend API:a välissä,
// eikä tehdä suoria kutsuja client-puolelta Supabaseen!
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY);
