
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rmkleyyzieacwltcbgzs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJta2xleXl6aWVhY3dsdGNiZ3pzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDA3NDgxMDUsImV4cCI6MjA1NjMyNDEwNX0.3uEku2-5p8MIVLEbjTuZkfIicMcdRH6O3k4dwxIFzi0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
